name: Auto Assign

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types:
      - opened
      - reopened

permissions:
  issues: write
  pull-requests: write

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  assign:
    runs-on: ubuntu-24.04

    steps:
      - name: Choose an Assignee
        run: echo ASSIGNEE=$(shuf -e HaradaTakayuki kazutan1230 Marukome0743 tanePON -n 1) >> $GITHUB_ENV

      - name: Assign Issue
        if: github.event_name == 'issues' && toJSON(github.event.issue.assignees) == '[]'
        run: gh issue edit ${{ github.event.issue.number }} --add-assignee ${{ env.ASSIGNEE }} --repo ${{ github.repository }}

      - name: Assign Pull Request
        if: github.event_name == 'pull_request_target' && toJSON(github.event.pull_request.assignees) == '[]'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-assignee ${{ env.ASSIGNEE }} --repo ${{ github.repository }}
